### ISSUE TITLE
No connected route for wifi network in AP mode

### ISSUE THREAD

**Issue by olly69** [mozilla-iot/gateway-wifi-setup#81]
I am using Raspbian 10 on a Raspberry pi nano.

When platforms/default.js starts the AP, wlan0 initially has an autoconfig IP address (169.x).  A few seconds later it gets changed to 192.168.220.1, but for some reason a "connected" route is not added to the routing table (for 192.168.220.0/24) meaning that devices on the wifi network cannot connect to the webserver.  There is a connected route for the original autoconfig address.  

I can get it to work correctly by modifying platforms/default.js as follows:

replace line:     'ifconfig wlan0 $IP; systemctl start hostapd; systemctl start dnsmasq',

with:    'ifconfig wlan0 $IP; systemctl start hostapd; systemctl start dnsmasq; route add -net 192.168.220.0/24 dev wlan0',

**Comment by mrstegeman** [comment]
Are you using this in a standalone fashion? We no longer use this particular repo for the gateway.

**Comment by olly69** [comment]
Yes, using it for a project unrelated to mozilla-iot - Just thought I'd reuse your hard work on this one!

**Comment by mrstegeman** [comment]
Ah, I see. The code here was merged into the gateway and has moved on considerably since then. If you're interested in seeing it, you can find the core functionality [here](https://github.com/mozilla-iot/gateway/blob/master/src/wifi-setup.js) and [here](https://github.com/mozilla-iot/gateway/blob/master/src/platform.js) (which calls into one of [these](https://github.com/mozilla-iot/gateway/tree/master/src/platforms)).

It would be a huge effort to bring that back into this repo for not a lot of gain, but please feel free to fork and update!
